version: "3.5"
services:
  jenkins:
    image: "jenkinsci/blueocean"
    hostname: "jenkins"
    container_name: "jenkins"
    ports:
      - "8000:8000"
      - "50000:50000"
    restart: always
    volumes:
      - jenkins_home:/var/jenkins_home
volumes:
  jenkins_home:
