version: '3.5'

services:
  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DB_EXTENSION: decoderbufs
    ports:
      - "5000:5432"
    volumes:
      - postgres:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network
    restart: unless-stopped
      
  pgadmin:
    image: dpage/pgadmin4
    hostname: pgadmin
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "sharma260985@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2019!"
    ports:
      - "16543:80"
    volumes:
      - pgadmin:/root/.pgadmin
    depends_on:
      - postgres
    networks:
      - postgres-compose-network

volumes:
  postgres:
  pgadmin:


networks: 
  postgres-compose-network:
    driver: bridge
    name: kafka_bridge

