version: '3.5'
services: 
  cp-kafkacat:
    image: confluentinc/cp-kafkacat:5.3.1
    hostname: cp-kafkacat
    container_name: cp-kafkacat
    environment:
      KSQL_BOOTSTRAP_SERVERS: PLAINTEXT://broker1:9092
    networks:
      - postgres-compose-network
    entrypoint: /bin/sh
    tty: true
    stdin_open: true
networks: 
    postgres-compose-network:
      name: kafka_bridge
      driver: bridge