version: "3.5"
services:
  connect:
    image: "debezium/connect"
    container_name: "connect"
    external_links:
      - zookeeper
      - broker
      - postgres
      - schema-registry
    hostname: "connect"
    ports:
      - "8083:8083"
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      KEY_CONVERTER: io.confluent.connect.avro.AvroConverter 
      VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter 
      INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter 
      INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter 
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081 
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081 
      BOOTSTRAP_SERVERS: 'broker:29092'
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    name: kafka_bridge
    driver: bridge
    

