apiVersion: v1
kind: Pod
metadata:
  name: esdc
  labels:
        app: esdc
spec:
  containers:
  - name: esdc
    image: jitendersharma/esdc-hw
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
