apiVersion: v1
kind: ReplicationController
metadata:
  name: esdc
spec:
  replicas: 10
  selector:
    app: esdc
  template:
    metadata:
      name: esdc
      labels:
        app: esdc
    spec:
      containers:
        - name: esdc-hw
          image: jitendersharma/esdc-hw
          ports:
            - containerPort: 8080

