apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp
spec:
  replicas: 10
  selector:
    app: myapp
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      containers:
        - name: esdc-hw
          image: jitendersharma/esdc-hw
          ports:
            - containerPort: 8080

